/**
 * @file    intent.types.ts
 * @desc    Enumeration of all supported natural-language intents.
 */

export enum AIIntent {
  GET_ASSET_OWNER = "GET_ASSET_OWNER",
  GET_AVAILABLE_ASSETS = "GET_AVAILABLE_ASSETS",
  GET_EMPLOYEE_ASSETS = "GET_EMPLOYEE_ASSETS",
  GET_DEPARTMENT_INFO = "GET_DEPARTMENT_INFO",
  GET_DASHBOARD_SUMMARY = "GET_DASHBOARD_SUMMARY",
  GET_REPORT = "GET_REPORT",
  GET_OVERDUE_ASSETS = "GET_OVERDUE_ASSETS",
  GET_ASSET_LOCATION = "GET_ASSET_LOCATION",
  UNKNOWN = "UNKNOWN",
}
